
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Sat Dec 04 17:24:25 EST 2010
//----------------------------------------------------

package com.smwatt.comp;

/** CUP generated class containing symbol constants. */
public class CTokenType {
  /* terminals */
  public static final int QMARK = 54;
  public static final int MINUS_MINUS = 40;
  public static final int SHORT = 60;
  public static final int SIGNED = 61;
  public static final int IDENTIFIER = 82;
  public static final int MOD_ASSIGN = 42;
  public static final int ENUMERATION_CONSTANT = 84;
  public static final int GT = 29;
  public static final int AMP = 2;
  public static final int VBAR_ASSIGN = 75;
  public static final int CONST = 12;
  public static final int FLOATING_CONSTANT = 86;
  public static final int SEMI = 59;
  public static final int REGISTER = 55;
  public static final int ENUM = 23;
  public static final int SIZEOF = 62;
  public static final int O_BRACK = 46;
  public static final int COMMA = 11;
  public static final int VBAR = 74;
  public static final int O_BRACE = 45;
  public static final int GT_EQ = 30;
  public static final int SLASH_ASSIGN = 64;
  public static final int O_PAREN = 47;
  public static final int LT = 36;
  public static final int INTEGER_CONSTANT = 85;
  public static final int LSH_ASSIGN = 35;
  public static final int DOUBLE = 21;
  public static final int STRUCT = 68;
  public static final int LT_EQ = 37;
  public static final int NOT = 43;
  public static final int AMP_ASSIGN = 4;
  public static final int TILDE = 70;
  public static final int CHARACTER_CONSTANT = 87;
  public static final int POUND = 52;
  public static final int XOR_ASSIGN = 81;
  public static final int ERROR = 89;
  public static final int FLOAT = 26;
  public static final int C_BRACK = 15;
  public static final int GOTO = 28;
  public static final int PLUS_PLUS = 50;
  public static final int RSH_ASSIGN = 58;
  public static final int C_BRACE = 14;
  public static final int C_PAREN = 16;
  public static final int MOD = 41;
  public static final int SLASH = 63;
  public static final int LONG = 33;
  public static final int PLUS = 48;
  public static final int STAR_ASSIGN = 66;
  public static final int NOT_EQUALS = 44;
  public static final int WHILE = 79;
  public static final int UNION = 72;
  public static final int TYPEDEF_NAME = 83;
  public static final int ASSIGN = 5;
  public static final int CHAR = 9;
  public static final int SWITCH = 69;
  public static final int DO = 18;
  public static final int FOR = 27;
  public static final int STAR = 65;
  public static final int MINUS_ASSIGN = 39;
  public static final int VOID = 77;
  public static final int EXTERN = 25;
  public static final int VBAR_VBAR = 76;
  public static final int RETURN = 56;
  public static final int RSH = 57;
  public static final int ELSE = 22;
  public static final int BREAK = 7;
  public static final int DOT = 19;
  public static final int INT = 32;
  public static final int EOF = 0;
  public static final int DEFAULT = 17;
  public static final int POUND_POUND = 53;
  public static final int MINUS = 38;
  public static final int error = 1;
  public static final int LSH = 34;
  public static final int POINTS_TO = 51;
  public static final int CONTINUE = 13;
  public static final int IF = 31;
  public static final int UNSIGNED = 73;
  public static final int DOT_DOT_DOT = 20;
  public static final int PLUS_ASSIGN = 49;
  public static final int COLON = 10;
  public static final int VOLATILE = 78;
  public static final int CASE = 8;
  public static final int STRING = 88;
  public static final int AMP_AMP = 3;
  public static final int STATIC = 67;
  public static final int TYPEDEF = 71;
  public static final int XOR = 80;
  public static final int AUTO = 6;
  public static final int EQUALS = 24;
}

